module Realms
  US_REALM_LIST=[
    "Aegwynn",
    "Aerie Peak",
    "Agamaggan",
    "Aggramar",
    "Akama",
    "Alexstrasza",
    "Alleria",
    "Altar of Storms",
    "Alterac Mountains",
    "Andorhal",
    "Anetheron",
    "Antonidas",
    "Anub'arak",
    "Anvilmar",
    "Arathor",
    "Archimonde",
    "Area 52",
    "ArgentDawn",
    "Arthas",
    "Arygos",
    "Auchindoun",
    "Azgalor",
    "Azjol-Nerub",
    "Azshara",
    "Azuremyst",
    "Baelgun",
    "Balnazzar",
    "Barthilas",
    "Black Dragonflight",
    "Blackhand",
    "Blackrock",
    "Blackwing Lair",
    "Blade's Edge",
    "Bladefist",
    "Bleeding Hollow",
    "Blood Furnace",
    "Bloodhoof",
    "Bloodscalp",
    "Bonechewer",
    "Borean Tundra",
    "Boulderfist",
    "Bronzebeard",
    "Burning Blade",
    "Burning Legion",
    "Caelestrasz",
    "Cairne",
    "Cenarion Circle",
    "Cenarius",
    "Cho'gall",
    "Chromaggus",
    "Coilfang",
    "Crushridge",
    "Daggerspine",
    "Dalaran",
    "Dalvengyr",
    "Dark Iron",
    "Darkspear",
    "Darrowmere",
    "Dath'Remar",
    "Dawnbringer",
    "Deathwing",
    "Demon Soul",
    "Dentarg",
    "Destromath",
    "Dethecus",
    "Detheroc",
    "Doomhammer",
    "Draenor",
    "Dragonblight",
    "Dragonmaw",
    "Drak'Tharon",
    "Drak'thul",
    "Draka",
    "Dreadmaul",
    "Drenden",
    "Dunemaul",
    "Durotan",
    "Duskwood",
    "Earthen Ring",
    "Echo Isles",
    "Eitrigg",
    "Eldre'Thalas",
    "Elune",
    "Emerald Dream",
    "Eonar",
    "Executus",
    "Exodar",
    "Farstriders",
    "Feathermoon",
    "Fenris",
    "Firetree",
    "Fizzcrank",
    "Frostmane",
    "Frostmourne",
    "Frostwolf",
    "Galakrond",
    "Garithos",
    "Garona",
    "Garrosh",
    "Ghostlands",
    "Gilneas",
    "Gnomeregan",
    "Gorgonnash",
    "Greymane",
    "Gul'dan",
    "Gundrak",
    "Gurubashi",
    "Haomarh",
    "Hellscream",
    "Hydraxis",
    "Hyjal",
    "Icecrown",
    "Illidan",
    "Jaedenar",
    "Jubei'Thos",
    "Kael'thas",
    "Kalecgos",
    "Kargath",
    "Kel'Thuzad",
    "Khadgar",
    "Khaz Modan",
    "Khaz'goroth",
    "Kil'jaeden",
    "Kilrogg",
    "Kirin Tor",
    "Korialstrasz",
    "Kul Tiras",
    "Laughing Skull",
    "Lightbringer",
    "Lightning's Blade",
    "Lightninghoof",
    "Llane",
    "Lothar",
    "Madoran",
    "Maelstrom",
    "Magtheridon",
    "Maiev",
    "Mal'Ganis",
    "Malfurion",
    "Malorne",
    "Malygos",
    "Mannoroth",
    "Medivh",
    "Misha",
    "Mok'Nathal",
    "Moon Guard",
    "Moonrunner",
    "Mug'thol",
    "Nagrand",
    "Nathrezim",
    "Nazgrel",
    "Nazjatar",
    "Ner'zhul",
    "Nesingwary",
    "Nordrassil",
    "Norgannon",
    "Onyxia",
    "Perenolde",
    "Proudmoore",
    "Quel'dorei",
    "Ravencrest",
    "Ravenholdt",
    "Rexxar",
    "Rivendare",
    "Runetotem",
    "Sargaras",
    "Saurfang",
    "Scarlet Crusade",
    "Scilla",
    "Sen'jin",
    "Sentinels",
    "Shadow Council",
    "Shadowmoon",
    "Shadowsong",
    "Shandris",
    "Shattered Halls",
    "Shattered Hand",
    "Shu'Halo",
    "Silver Hand",
    "Sisters of Elune",
    "Skullcrusher",
    "Skywall",
    "Smolderthorn",
    "Spinebreaker",
    "Spirestone",
    "Staghelm",
    "Steamwheedle Cartel",
    "Stonemaul",
    "Stormrage",
    "Stormreaver"
  ]
end
